### ISSUE TITLE
bluetooth_speaker.py, AttributeError: 'NoneType' object has no attribute 'getvolume'

### ISSUE THREAD

**Issue by skynetforcats** [dgomes/home-assistant-custom-components#1]
Hi thanks for this custom component. Just what I need.
However I can't seem to get it to work.
Get this error:

`  File "/home/homeassistant/.homeassistant/custom_components/media_player/bluetooth_speaker.py", line 89, in update
    self._volume = float(self.mixer.getvolume()[0])/100
AttributeError: 'NoneType' object has no attribute 'getvolume'`

The entity shows up with state 'on' and attributes:
supported_features: 1548
is_volume_muted: false
volume_level: 0
friendly_name: Bluetooth Speaker

My configuration.yaml:
media_player:
- platform: bluetooth_speaker
  name: Bluetooth Speaker #OPTIONAL
  device: '10:B7:F6:28:63:D7' #REQUIRED: this string is what shows up when you discover a new device
  step: 0.05 #OPTIONAL: steps increase/decrease volume

**Comment by skynetforcats** [comment]
Found the cause of the issue.
"device" needs to be the name of the mixer specifically. 

> homeassistant@hassbian:/home/pi $ amixer -D bluealsa
Simple mixer control 'Jabra Solemate Min | Battery',0
  Capabilities: pvolume pvolume-joined
  Playback channels: Mono
  Limits: Playback 0 - 100
  Mono: Playback 100 [100%]
Simple mixer control '**Jabra Solemate Mini v - A2DP**',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 127
  Mono:
  Front Left: Playback 127 [100%] [on]
  Front Right: Playback 126 [99%] [on]
Simple mixer control 'Jabra Solemate Mini v8 - SCO',0
  Capabilities: pvolume pvolume-joined cvolume cvolume-joined pswitch pswitch-joined cswitch c                                  switch-joined
  Playback channels: Mono
  Capture channels: Mono
  Limits: Playback 0 - 15 Capture 0 - 15
  Mono: Playback 15 [100%] [on] Capture 15 [100%] [on]

**Comment by dgomes** [comment]
Good :)
